-- MySQL Script generated by MySQL Workbench
-- 10/19/17 15:40:04
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema meu_trabalho
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `meu_trabalho` ;
CREATE SCHEMA IF NOT EXISTS `meu_trabalho` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `meu_trabalho` ;

-- -----------------------------------------------------
-- Table `meu_trabalho`.`ocupacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meu_trabalho`.`ocupacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ocupacao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meu_trabalho`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meu_trabalho`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `nascimento` DATE NOT NULL,
  `telefone` VARCHAR(14) NULL,
  `sexo` INT(1) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `data_atualizacao` DATETIME NOT NULL,
  `ocupacao_id` INT NOT NULL,
  PRIMARY KEY (`id`, `ocupacao_id`),
  INDEX `fk_usuario_ocupacao_idx` (`ocupacao_id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `fk_usuario_ocupacao`
    FOREIGN KEY (`ocupacao_id`)
    REFERENCES `meu_trabalho`.`ocupacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meu_trabalho`.`trabalho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meu_trabalho`.`trabalho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(150) NULL,
  `descricao` TEXT NULL,
  `data_cadastro` DATETIME NULL,
  `data_entrega` DATE NULL,
  `publicado` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meu_trabalho`.`membros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meu_trabalho`.`membros` (
  `trabalho_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`trabalho_id`, `usuario_id`),
  INDEX `fk_trabalho_has_usuario_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_trabalho_has_usuario_trabalho1_idx` (`trabalho_id` ASC),
  CONSTRAINT `fk_trabalho_has_usuario_trabalho1`
    FOREIGN KEY (`trabalho_id`)
    REFERENCES `meu_trabalho`.`trabalho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trabalho_has_usuario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `meu_trabalho`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meu_trabalho`.`etiqueta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meu_trabalho`.`etiqueta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meu_trabalho`.`etiqueta_trabalho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meu_trabalho`.`etiqueta_trabalho` (
  `etiqueta_id` INT NOT NULL,
  `trabalho_id` INT NOT NULL,
  PRIMARY KEY (`etiqueta_id`, `trabalho_id`),
  INDEX `fk_etiqueta_has_trabalho_trabalho1_idx` (`trabalho_id` ASC),
  INDEX `fk_etiqueta_has_trabalho_etiqueta1_idx` (`etiqueta_id` ASC),
  CONSTRAINT `fk_etiqueta_has_trabalho_etiqueta1`
    FOREIGN KEY (`etiqueta_id`)
    REFERENCES `meu_trabalho`.`etiqueta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_etiqueta_has_trabalho_trabalho1`
    FOREIGN KEY (`trabalho_id`)
    REFERENCES `meu_trabalho`.`trabalho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meu_trabalho`.`arquivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meu_trabalho`.`arquivo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `caminho` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meu_trabalho`.`arquivo_trabalho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meu_trabalho`.`arquivo_trabalho` (
  `arquivo_id` INT NOT NULL,
  `trabalho_id` INT NOT NULL,
  PRIMARY KEY (`arquivo_id`, `trabalho_id`),
  INDEX `fk_arquivo_has_trabalho_trabalho1_idx` (`trabalho_id` ASC),
  INDEX `fk_arquivo_has_trabalho_arquivo1_idx` (`arquivo_id` ASC),
  CONSTRAINT `fk_arquivo_has_trabalho_arquivo1`
    FOREIGN KEY (`arquivo_id`)
    REFERENCES `meu_trabalho`.`arquivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_arquivo_has_trabalho_trabalho1`
    FOREIGN KEY (`trabalho_id`)
    REFERENCES `meu_trabalho`.`trabalho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
